cursor #e1e2e4
cursor_text_color #c0c8cc

foreground            #e1e2e4
background            #111415
selection_foreground  #20333b
selection_background  #b6cad4
url_color             #9acee6

color0   #111415
color1   #ff729f
color2   #73e680
color3   #fff672
color4   #83bfda
color5   #29566a
color6   #9acee6
color7   #e3edf1
color8   #8a9295
color9   #ff9fbe
color10  #a5ffaf
color11  #fff9a5
color12  #b5e6fd
color13  #c4ecff
color14  #d9f3ff
color15  #f8fdff
