cursor #e3e2e2
cursor_text_color #c1c8c9

foreground            #e3e2e2
background            #121414
selection_foreground  #273234
selection_background  #bdc9cb
url_color             #ebfcff

color0   #121414
color1   #ff72a2
color2   #7fff8b
color3   #fff572
color4   #dbeef2
color5   #657376
color6   #ebfcff
color7   #effcff
color8   #99a3a5
color9   #ff9fc0
color10  #a5ffae
color11  #fff8a5
color12  #eefcff
color13  #f1fcff
color14  #f6fdff
color15  #f8fdff
