cursor #e3e1e9
cursor_text_color #c5c5d3

foreground            #e3e1e9
background            #121318
selection_foreground  #282f4d
selection_background  #bec5ea
url_color             #b7c4ff

color0   #121318
color1   #ff7297
color2   #7fff94
color3   #fff972
color4   #a0aef2
color5   #384376
color6   #b7c4ff
color7   #eff2ff
color8   #999ba5
color9   #ff9fb8
color10  #a5ffb4
color11  #fffba5
color12  #c1ccff
color13  #ccd5ff
color14  #dee4ff
color15  #f8f9ff
