ELECTRON_OZONE_PLATFORM_HINT=auto
TERMINAL=kitty
XDG_CACHE_HOME=$HOME/.cache
XDG_STATE_HOME=$HOME/.local/state
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx
SDL_IM_MODULE=fcitx
GLFW_IM_MODULE=fcitx
INPUT_METHOD=fcitx
# LIBVA_DRIVER_NAME unset — let browser pick based on display GPU
