#!/bin/sh
# 仅在本机（lildengzi-cachyos）应用硬件相关覆盖。
# 其余机器运行本脚本直接退出，不影响仓库通用配置。
set -e
. "$(dirname "$0")/lib.sh"

HOST=$(hostname)

case "$HOST" in
    lildengzi-cachyos)
        echo "=== 应用 lildengzi-cachyos 硬件覆盖 ==="
        # 输出: HDMI-A-1 主屏 + eDP-2 副屏
        mkdir -p "$HOME/.config/niri/dms"
        cat > "$HOME/.config/niri/dms/outputs.kdl" << 'EOF'
// Auto-generated by DMS - do not edit manually

output "HDMI-A-1" {
    mode "1920x1080@165.000"
    scale 1
    position x=0 y=0
}

output "eDP-2" {
    mode "1920x1080@144.003"
    scale 1
    position x=1920 y=0
}
EOF
        echo "  已写入 outputs.kdl (HDMI-A-1 + eDP-2)"
        # DMS ddc i2c-5
        if [ -f "$HOME/.config/DankMaterialShell/settings.json" ]; then
            sed -i 's/"deviceName": "ddc:i2c-3"/"deviceName": "ddc:i2c-5"/' \
                "$HOME/.config/DankMaterialShell/settings.json"
            echo "  已应用 ddc:i2c-5"
        fi
        ;;
    *)
        echo "非本机 ($HOST)，跳过硬件覆盖。"
        ;;
esac