[colors.primary]
background = '#121414'
foreground = '#e3e2e2'

[colors.selection]
text = '#e3e2e2'
background = '#c2e2e8'

[colors.cursor]
text = '#121414'
cursor = '#ebfcff'

[colors.normal]
black   = '#121414'
red     = '#ff72a2'
green   = '#7fff8b'
yellow  = '#fff572'
blue    = '#dbeef2'
magenta = '#657376'
cyan    = '#ebfcff'
white   = '#effcff'

[colors.bright]
black   = '#99a3a5'
red     = '#ff9fc0'
green   = '#a5ffae'
yellow  = '#fff8a5'
blue    = '#eefcff'
magenta = '#f1fcff'
cyan    = '#f6fdff'
white   = '#f8fdff'
